name: CI
on: push

jobs:
  ci:
    name: Jest Unit Tests, Type Checking, Linting, Playwright End to End Tests
    runs-on: ubuntu-latest # or macos-latest, windows-latest
    timeout-minutes: 30
    # TODO: Update environment variables with your own database credentials
    env:
      PGHOST: localhost
      PGDATABASE: next_js_task_manager
      PGUSERNAME: next_js_task_manager
      PGPASSWORD: next_js_task_manager
      DATABASE_URL: ="postgresql://next_js_task_manager:next_js_task_manager@localhost:5432/next_js_task_manager?schema=next_js_task_manager"

    steps:
      - name: Start preinstalled PostgreSQL on Ubuntu
        run: |
          sudo systemctl start postgresql.service
          pg_isready
      - name: Create database user
        run: |
          sudo -u postgres psql --command="CREATE USER $PGUSERNAME PASSWORD '$PGPASSWORD'" --command="\du"
      - name: Create database and allow user
        run: |
          sudo -u postgres createdb --owner=$PGUSERNAME $PGDATABASE
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4

      # Use the official setup-node action (sets up Node.js):
      # https://github.com/actions/setup-node
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
      - name: Jest unit tests
        run: pnpm jest
      - name: Run database migrations
        run: pnpm migrate up
      - name: Build Next.js app (types needed for TSC and ESLint)
        run: pnpm build
      - name: Check TypeScript Types
        run: pnpm tsc
      - name: Lint with ESLint
        run: pnpm eslint . --max-warnings 0
      - name: Lint with Stylelint
        run: pnpm stylelint '**/*.{css,scss,less,js,tsx}'

      # Cache and install Playwright browser binaries, modified version of:
      # https://github.com/microsoft/playwright/issues/7249#issuecomment-1154603556
      # https://github.com/microsoft/playwright/issues/7249#issuecomment-1385567519
      # https://playwrightsolutions.com/playwright-github-action-to-cache-the-browser-binaries/
      - name: Get installed Playwright version for cache key
        id: get_playwright_version
        run: echo "::set-output name=playwright_version::$(yq eval '.version' --output-format=yaml ./node_modules/@playwright/test/package.json)"
      - name: Cache Playwright browser binaries
        uses: actions/cache@v4
        id: playwright-browser-cache
        with:
          path: |
            ~/.cache/ms-Playwright
          key: ${{ runner.os }}-playwright-${{ steps.get_playwright_version.outputs.playwright_version }}
      - name: Install Playwright browsers only on cache miss
        run: pnpm playwright install --with-deps chromium
        if: steps.playwright-browser-cache.outputs.cache-hit != 'true'

      - name: Run tests
        run: pnpm playwright test
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-screenshots-videos
          path: playwright/test-results/

  cd:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: ci
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
